from routes.auth      import auth_bp
from routes.admin     import admin_bp
from routes.company   import company_bp
from routes.student   import student_bp
from routes.jobs      import jobs_bp
from routes.analytics import analytics_bp
from routes.analytics import analytics_bp
from routes.ats       import ats_bp
from routes.analytics import analytics_bp
from routes.ats       import ats_bp
