"""
celery_tasks/reports.py
------------------------
Runs on the 1st of every month at 07:00 IST via Celery Beat.

Generates an HTML placement activity report for the Admin and
emails it as an inline HTML body + plain-text fallback.
"""

import logging
from datetime import datetime, timezone
from calendar import month_name

from celery_app import celery
from utils.notifications import send_email_html

logger = logging.getLogger(__name__)


# ── HTML report template ──────────────────────────────────────────────────────

REPORT_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  body        {{ font-family: Arial, sans-serif; color: #333; margin: 0; padding: 20px; }}
  h1          {{ color: #1a56db; border-bottom: 2px solid #1a56db; padding-bottom: 8px; }}
  h2          {{ color: #374151; margin-top: 28px; }}
  .stat-grid  {{ display: flex; flex-wrap: wrap; gap: 16px; margin: 16px 0; }}
  .stat-card  {{ background: #f3f4f6; border-radius: 8px; padding: 16px 24px;
                 min-width: 150px; text-align: center; }}
  .stat-num   {{ font-size: 2rem; font-weight: 700; color: #1a56db; }}
  .stat-label {{ font-size: 0.85rem; color: #6b7280; margin-top: 4px; }}
  table       {{ width: 100%; border-collapse: collapse; margin-top: 12px; }}
  th          {{ background: #1a56db; color: #fff; padding: 10px 12px;
                 text-align: left; font-size: 0.85rem; }}
  td          {{ padding: 9px 12px; border-bottom: 1px solid #e5e7eb;
                 font-size: 0.85rem; }}
  tr:nth-child(even) td {{ background: #f9fafb; }}
  .badge      {{ display: inline-block; padding: 2px 8px; border-radius: 12px;
                 font-size: 0.75rem; font-weight: 600; }}
  .badge-s    {{ background: #d1fae5; color: #065f46; }}
  .badge-r    {{ background: #fee2e2; color: #991b1b; }}
  .footer     {{ margin-top: 32px; font-size: 0.8rem; color: #9ca3af; }}
</style>
</head>
<body>
<h1>Monthly Placement Activity Report</h1>
<p><strong>Period:</strong> {month_name} {year} &nbsp;|&nbsp;
   <strong>Generated:</strong> {generated_at}</p>

<h2>Overview</h2>
<div class="stat-grid">
  <div class="stat-card">
    <div class="stat-num">{total_drives}</div>
    <div class="stat-label">Drives Conducted</div>
  </div>
  <div class="stat-card">
    <div class="stat-num">{total_applications}</div>
    <div class="stat-label">Applications Received</div>
  </div>
  <div class="stat-card">
    <div class="stat-num">{total_selected}</div>
    <div class="stat-label">Students Placed</div>
  </div>
  <div class="stat-card">
    <div class="stat-num">{total_companies}</div>
    <div class="stat-label">Companies Active</div>
  </div>
  <div class="stat-card">
    <div class="stat-num">{placement_rate}%</div>
    <div class="stat-label">Placement Rate</div>
  </div>
</div>

<h2>Placement Drives This Month</h2>
{drives_table}

<h2>Top Companies by Placements</h2>
{companies_table}

<h2>Recent Placements</h2>
{placements_table}

<p class="footer">
  This report was auto-generated by the Placement Portal on {generated_at}.
  Do not reply to this email.
</p>
</body>
</html>
"""


def _build_table(headers, rows, empty_msg="No data available."):
    if not rows:
        return f'<p style="color:#6b7280">{empty_msg}</p>'
    ths = "".join(f"<th>{h}</th>" for h in headers)
    trs = ""
    for row in rows:
        tds = "".join(f"<td>{cell}</td>" for cell in row)
        trs += f"<tr>{tds}</tr>"
    return f"<table><thead><tr>{ths}</tr></thead><tbody>{trs}</tbody></table>"


@celery.task(name="celery_tasks.reports.generate_monthly_placement_report",
             bind=True, max_retries=2, default_retry_delay=600)
def generate_monthly_placement_report(self):
    """
    Generates HTML report for the previous month and emails to admin.
    Can also be triggered manually via the /api/jobs/report endpoint.
    """
    try:
        from app import create_app, db
        from models.models import (PlacementDrive, Application, Placement,
                                   Company, DriveStatus, ApplicationStatus)
        from config import Config
        from sqlalchemy import func
        import calendar

        app = create_app()
        with app.app_context():
            now          = datetime.now(timezone.utc)
            # Report covers last month
            first_this   = now.replace(day=1, hour=0, minute=0, second=0)
            if first_this.month == 1:
                first_prev = first_this.replace(year=first_this.year - 1, month=12)
            else:
                first_prev = first_this.replace(month=first_this.month - 1)

            last_prev = first_this

            report_month = first_prev.month
            report_year  = first_prev.year

            # ── Aggregate stats ──────────────────────────────────────────

            drives = (PlacementDrive.query
                      .filter(PlacementDrive.created_at >= first_prev)
                      .filter(PlacementDrive.created_at < last_prev)
                      .all())

            drive_ids = [d.id for d in drives]

            total_applications = (Application.query
                                  .filter(Application.drive_id.in_(drive_ids))
                                  .count()) if drive_ids else 0

            total_selected = (Application.query
                              .filter(Application.drive_id.in_(drive_ids))
                              .filter(Application.status.in_(
                                  [ApplicationStatus.SELECTED, "placed"]))
                              .count()) if drive_ids else 0

            active_companies = len({d.company_id for d in drives})

            placement_rate = (
                round(total_selected / total_applications * 100, 1)
                if total_applications else 0
            )

            # ── Drives table ─────────────────────────────────────────────

            drives_rows = []
            for d in drives:
                app_count = len(d.applications)
                sel_count = sum(1 for a in d.applications
                                if a.status in [ApplicationStatus.SELECTED, "placed"])
                drives_rows.append([
                    d.id,
                    d.job_title,
                    d.company.name if d.company else "—",
                    d.status,
                    app_count,
                    f'<span class="badge badge-s">{sel_count} placed</span>',
                ])

            drives_table = _build_table(
                ["#", "Job Title", "Company", "Status", "Applicants", "Placed"],
                drives_rows,
                "No drives created this month."
            )

            # ── Companies table ───────────────────────────────────────────

            company_stats = {}
            for d in drives:
                cname = d.company.name if d.company else "Unknown"
                if cname not in company_stats:
                    company_stats[cname] = {"drives": 0, "apps": 0, "placed": 0}
                company_stats[cname]["drives"] += 1
                company_stats[cname]["apps"]   += len(d.applications)
                company_stats[cname]["placed"] += sum(
                    1 for a in d.applications
                    if a.status in [ApplicationStatus.SELECTED, "placed"]
                )

            co_rows = sorted(
                [[n, v["drives"], v["apps"], v["placed"]]
                 for n, v in company_stats.items()],
                key=lambda x: -x[3]
            )
            companies_table = _build_table(
                ["Company", "Drives", "Applicants", "Placed"],
                co_rows, "No companies active this month."
            )

            # ── Recent placements table ───────────────────────────────────

            placements = (Placement.query
                          .filter(Placement.created_at >= first_prev)
                          .filter(Placement.created_at < last_prev)
                          .order_by(Placement.created_at.desc())
                          .limit(20).all())

            pl_rows = [[
                p.student.full_name if p.student else "—",
                p.company.name if p.company else "—",
                p.position or "—",
                f"₹{p.salary} LPA" if p.salary else "—",
                p.joining_date or "TBD",
            ] for p in placements]

            placements_table = _build_table(
                ["Student", "Company", "Position", "Salary", "Joining Date"],
                pl_rows, "No placements recorded this month."
            )

            # ── Render HTML ───────────────────────────────────────────────

            html = REPORT_TEMPLATE.format(
                month_name       = month_name[report_month],
                year             = report_year,
                generated_at     = now.strftime("%d %b %Y %I:%M %p IST"),
                total_drives     = len(drives),
                total_applications = total_applications,
                total_selected   = total_selected,
                total_companies  = active_companies,
                placement_rate   = placement_rate,
                drives_table     = drives_table,
                companies_table  = companies_table,
                placements_table = placements_table,
            )

            # ── Save HTML file ─────────────────────────────────────────────

            import os
            export_dir = app.config.get(
                "EXPORT_FOLDER",
                os.path.join(os.path.dirname(__file__), "..", "exports"))
            os.makedirs(export_dir, exist_ok=True)
            filename = f"report_{report_year}_{report_month:02d}.html"
            filepath = os.path.join(export_dir, filename)
            with open(filepath, "w", encoding="utf-8") as fh:
                fh.write(html)

            # ── Email to admin ─────────────────────────────────────────────

            send_email_html(
                to      = Config.ADMIN_EMAIL,
                subject = f"Monthly Placement Report — {month_name[report_month]} {report_year}",
                html    = html,
                plain   = (
                    f"Monthly Placement Report\n"
                    f"Period: {month_name[report_month]} {report_year}\n"
                    f"Drives: {len(drives)} | Applications: {total_applications} "
                    f"| Placed: {total_selected} | Rate: {placement_rate}%\n"
                    f"See attached HTML report or log into the portal."
                ),
            )

            logger.info("Monthly report generated: %s", filename)
            return {
                "filename":        filename,
                "total_drives":    len(drives),
                "total_placed":    total_selected,
                "placement_rate":  placement_rate,
            }

    except Exception as exc:
        logger.error("generate_monthly_placement_report failed: %s", exc)
        raise self.retry(exc=exc)
